using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AlgoDemos.AStar
{
    public class AstarAlgo
    {
        public int ShortestPathBinaryMatrix_code_gen(int[][] grid)
        {
            int n = grid.Length;
            if (grid[0][0] == 1 || grid[n - 1][n - 1] == 1) return -1;
            var directions = new int[][] { new int[] { 0, 1 }, new int[] { 1, 0 }, new int[] { 0, -1 }, new int[] { -1, 0 }, new int[] { 1, 1 }, new int[] { -1, -1 }, new int[] { -1, 1 }, new int[] { 1, -1 } };
            var pq = new PriorityQueue<(int x, int y), int>();
            pq.Enqueue((0, 0), 1);
            var visited = new HashSet<(int x, int y)>();
            visited.Add((0, 0));
            while (pq.Count > 0)
            {
                var (x, y) = pq.Dequeue();
                if (x == n - 1 && y == n - 1) return grid[x][y];
                foreach (var dir in directions)
                {
                    int nx = x + dir[0];
                    int ny = y + dir[1];
                    if (nx >= 0 && nx < n && ny >= 0 && ny < n && grid[nx][ny] == 0 && !visited.Contains((nx, ny)))
                    {
                        visited.Add((nx, ny));
                        grid[nx][ny] = grid[x][y] + 1;
                        pq.Enqueue((nx, ny), grid[nx][ny] + Math.Abs(n - 1 - nx) + Math.Abs(n - 1 - ny));
                    }
                }
            }
            return -1;
        }

        int _n;
        int[][] _grid;
        double[][] _weights;
        /// <summary>
        /// Given anxn grid, where each cell is either 0 (empty) or 1 (blocked), return the length of the 
        /// shortest clear path (path follows only the cells with 0) from top-left to bottom-right. If there is no clear path, return -1.
        /// Each cell of hte path has value 0 or 1 and can move to 8 adjacent cells (horizontally, vertically, diagonally). The length of a clear path is the number of cells in the path including the start and end cells.
        /// A* algorithm (which is Dijkstra + heuristic) can be used. It is similar to Dijkstra's algorithm, but instead of using a regular queue, we use a priority queue that prioritizes nodes based on their estimated total cost (g(n) + h(n)), where g(n) is the cost from the start node to the current node and h(n) is the heuristic estimate of the cost from the current node to the goal node. In this case, we can use the Manhattan distance as our heuristic function.
        /// In A* algorithm, if we use consistent heuristic then,
        /// when A* agorithm expands a node the optimal path to that node has already been found out. Proof by contradiction -
        /// Suppose for the sake of contradiction that when A* expands n, the optimal path has not 
        /// been found.Then, by the graph separation property, there must exist another node n' on the 
        /// optimal path to n in the frontier set. This means f(n) < f(n') (since we dont have any negative cost if n' is 
        /// on path to n this is not possible sine f(n) has to be greater than f(n`). This is contradiction =>
        /// our property hold, i.e., any node being expanded in A* has already got optimal cost of path to it generated.</f>
        /// Note - In the study of path-finding problems in artificial intelligence, a heuristic 
        /// function is said to be consistent, or monotone, if its estimate is always less than or 
        /// equal to the estimated distance from any neighbouring vertex to the goal, plus the cost of 
        /// reaching that neighbour. +> self-note - Manhattna distance does not seem to be consisten., take 6x6 grid, and points (1,3)->(2,4) jump,
        /// the h((1,3) ) = 6 while h((2,4)) = 4 and cost of jump from (1,3) to (2,4) is 1, so h((1,3)) > h((2,4)) + cost((1,3)->(2,4)) and this is not consistent heuristic. But it is admissible heuristic since it never overestimates the cost to reach the goal.
        /// So Manhattan distance is Consistent Heuristic when you can only move left,right,up,downb & not diagonally. In this problem since we can move diagonally also
        /// we will have to use Euclidean distance as heuristic, which is consistent heuristic in this case.
        /// self-note - I find that for test case failed - [[0, 0, 0, 0, 1, 1], [0, 1, 0, 0, 1, 0], [1, 1, 0, 1, 0, 0], [0, 1, 0, 0, 1, 1], [0, 1, 0, 0, 0, 1], [0, 0, 1, 0, 0, 0]]
        /// since manhattan lgic is not consistent when diagonal traevl is allowed.
        /// since both these cells are totalling to 10 the algo (generated by copilot) is taking one of them arbitrarily grid[3][3] wrongly.
        /// Added addnl logic by me - replace Manhattan distance with Euclidean distance.
        /// Even this failed one huge leetcode testcase. I suspect this is because when we have multiple nodes with same f(n) value in the priority queue, then we are not guaranteed to pick the one with lowest h(n) value, which is required for A* algorithm to work correctly.
        /// So added addnl logic to check if there are multiple nodes with same f(n) value in the priority queue, then we will pick the one with lowest h(n) value.
        /// Finally leetcode 90/90 testcases pass - Runtime though 103ms beats only 5.04% and memory 57MB beats 11.51%
        /// Later I knew that I could even have used "diganola distance" which is max of dx, dy instead of Euclidean distance as heuristic, which is also consistent heuristic in this case since we can move diagonally. This would have reduced the time complexity of calculating the heuristic and might have improved the runtime performance.
        /// </summary>
        /// <param name="grid"></param>
        /// <returns></returns>
        public int ShortestPathBinaryMatrix(int[][] grid)
        {
            _n = grid.Length;
            _grid = grid;
            _weights = new double[_n][];
            for (int y=0;y<_n;y++)
            {
                _weights[y] = new double[_n];
            }
            
            // we have to always follow o's path and avoid 1's
            // once we have visited a ndoe, we will not visit it again ,
            // so we can modify the grid to store the distance from the start point (where 0's were there originally)
            if (_n == 0 || _grid[0][0] == 1 || _grid[_n - 1][_n - 1] == 1) return -1;

            PriorityQueue<(int x, int y), (double f, double h)> pq = new();
            Dictionary<(int, int), (int, int)> path = new();
            HashSet<(int x, int y)> visited = new();

            var getDistance = (int x1, int y1, int x2, int y2) =>
                Math.Sqrt(Math.Pow(x2 - x1, 2) + Math.Pow(y2 - y1, 2));
            for(int i = 0; i < _n; i++)
            {
                for (int j = 0; j < _n; j++)
                {
                    _weights[i][j] = getDistance(i, j, _n - 1, _n - 1);
                }
            }


            
            pq.Enqueue((0, 0), (1+ _weights[0][0], _weights[0][0]));
            // 8 possible directions to move at any node (providing boundary is not hit)
            var directions = new int[][] { new int[] { 0, 1 }, new int[] { 1, 0 }, new int[] { 0, -1 }, new int[] { -1, 0 }, new int[] { 1, 1 }, new int[] { -1, -1 }, new int[] { -1, 1 }, new int[] { 1, -1 } };
            while (pq.Count > 0)
            {
                var (x, y) = pq.Dequeue();
                if (pq.Count > 0) {
                    var (xTemp, yTemp) = pq.Peek();
                    //check if 
                }
                if (x == _n - 1 && y == _n - 1)
                {
                    PrintPath(path);
                    return _grid[x][y] + 1; // reached destination node - add 1 since we are going to destination cell too
                }
                foreach (var dir in directions)
                {
                    int nx = x + dir[0];
                    int ny = y + dir[1];
                    // new node is valid only for valid values of nx & ny, and
                    // if it is not a wall (1) and
                    // if it is not visited before
                    if (nx >= 0 && nx < _n && ny >= 0 && ny < _n && 
                        _grid[nx][ny] == 0 && !visited.Contains((nx, ny)))
                    {
                        visited.Add((nx, ny));
                        _grid[nx][ny] = _grid[x][y] + 1; // store the distance (number of cells traversed) from start node
                        path[(nx, ny)] = (x, y);
                        pq.Enqueue((nx, ny), (_grid[nx][ny] + _weights[nx][ny], _weights[nx][ny])); // f(n) = g(n) + h(n) where heuristic is Euclidean distance
                    }
                }
            }
            
            // no path found
            return -1;

        }

        /// <summary>
        /// This code failed for testcase -
        /// [[0,0,0,0,1,1,1,1,0],[0,1,1,0,0,0,0,1,0],[0,0,1,0,0,0,0,0,0],[1,1,0,0,1,0,0,1,1],[0,0,1,1,1,0,1,0,1],[0,1,0,1,0,0,0,0,0],[0,0,0,1,0,1,0,0,0],[0,1,0,1,1,0,0,0,0],[0,0,0,0,0,1,0,1,0]]
        /// Expected output 12 while my result was 11. This is because when we have multiple nodes with same f(n) value in the priority queue, then we are not guaranteed to pick the one with lowest h(n) value, which is required for A* algorithm to work correctly.
        /// GeeksofGeeks gives a limitation - Although being the best path finding algorithm around, A* Search Algorithm doesn’t produce the shortest path always, as it relies heavily on heuristics / approximations to calculate - h
        /// For leet code problem the euclidean distance passed all testcases. The manhattan, diagonal ueristics failed (most
        /// probably because of f values that are same for multiple ndoes. The algo selects wrong
        /// node to expand on. It also states that this algorithm can also be applied on graphs, not just grids.
        /// Worst case complexity of A* is O(E) where E is number of edges in the graph.
        /// When I added a tie-breaker logic which computes the vector cross-product between the start to goal vector and the current point to goal vector.
        /// </summary>
        /// <param name="grid"></param>
        /// <returns></returns>
        public int ShortestPathBinaryMatrixDiagonalDistance(int[][] grid)
        {
            int n = grid.Length;

            // we have to always follow o's path and avoid 1's
            // once we have visited a ndoe, we will not visit it again ,
            // so we can modify the grid to store the distance from the start point (where 0's were there originally)
            if (n == 0 || grid[0][0] != 0 || grid[n - 1][n - 1] != 0) return -1;

            /*
            Console.WriteLine("given problem:");
            for (int i = 0; i < n; i++)
            {
                for (int j = 0; j < n; j++)
                {
                    Console.Write($"{grid[i][j]} ");
                }
                Console.WriteLine();
            }
            */
            Dictionary<(int, int), int> f_n = new();
            f_n[(0,0)] = 1; // this cost does not matter since first vertex is dequed first and it will be the only one in the queue when it is dequed

            /*
            var h_n = new int[n][];
            var tie_breaker_weights = new double[n][];
            for (int y = 0; y < n; y++)
            {
                h_n[y] = new int[n];
                tie_breaker_weights[y] = new double[n];
            }

            for (int x = 0; x < n; x++)
            {
                for (int y = 0; y < n; y++)
                {
                    h_n[x][y] = Math.Max(Math.Abs(x - (n - 1)), Math.Abs(y - (n - 1)));
                    tie_breaker_weights[x][y] = TieBreakerh_n(x, y, n - 1, n - 1);
                }
            }
            */


            PriorityQueue<(int x, int y, int steps), (int f_n, double h)> pq = new();
            Dictionary<(int, int), (int, int)> path = new();
            HashSet<(int x, int y)> visited = new();

            pq.Enqueue((0, 0, 1), (f_n[(0,0)], TieBreakerh_n(0, 0, n - 1, n - 1)));
            
            // 8 possible directions to move at any node (providing boundary is not hit)
            var directions = new int[][] { new int[] { 0, 1 }, new int[] { 1, 0 }, 
                new int[] { 0, -1 }, new int[] { -1, 0 }, 
                new int[] { 1, 1 }, new int[] { -1, -1 }, 
                new int[] { -1, 1 }, new int[] { 1, -1 } };
            while (pq.Count > 0)
            {
                var (x, y, steps) = pq.Dequeue();
                
                if (x == n - 1 && y == n - 1)
                {
                    // PrintPathAndWeights(grid, path, weights, visited, tie_breaker_weights);
                    return steps; // reached destination node
                }
                foreach (var dir in directions)
                {
                    int nx = x + dir[0];
                    int ny = y + dir[1];
                    // new node is valid only for valid values of nx & ny, and
                    // if it is not a wall (1) and
                    // if it is not visited before
                    if (nx >= 0 && nx < n && ny >= 0 && ny < n &&
                        grid[nx][ny] == 0 
                        && !visited.Contains((nx, ny))
                        )
                    {
                        visited.Add((nx, ny));
                        int new_f_n = steps + 1 + Math.Max(Math.Abs(nx - (n - 1)), Math.Abs(ny - (n - 1))); ; 
                        if(f_n.TryGetValue((nx, ny), out int existing_f_n) && existing_f_n <= new_f_n)
                        {
                            Console.WriteLine($"skipping one node ({nx}, {ny}) since it is already in the queue with lesser f(n) value");
                            continue; // no need to enqueue this node since it is already in the queue and with lesser cost
                        }
                        f_n[(nx, ny)] = new_f_n;
                        path[(nx, ny)] = (x, y);
                        pq.Enqueue((nx, ny, steps+1), (new_f_n, TieBreakerh_n(nx, ny, n - 1, n - 1))); // f(n) = g(n) + h(n) where heuristic is Diagonal distance
                    }
                    /*
                    else
                    {
                        if(visited.Contains((nx, ny)))
                        {
                            Console.WriteLine($"Already visited node {(nx, ny)}. prev cost - {grid[nx][ny]}. current cost - {grid[x][y] + 1}");
                        }
                        else if (nx >= 0 && nx < n && ny >= 0 && ny < n)
                        {
                            Console.WriteLine($"Node {(nx, ny)} is a wall");
                        }
                        else
                        {
                            Console.WriteLine($"Node {(nx, ny)} is out of bounds");
                        }
                    }
                    */
                }
            }

            // no path found
            return -1;

        }


        // 8 possible directions to move at any node (providing boundary is not hit)
        public static readonly int[][] _directions = new int[][] {
                new int[] { 0, 1 }, new int[] { 1, 0 },
                new int[] { 0, -1 }, new int[] { -1, 0 },
                new int[] { 1, 1 }, new int[] { -1, -1 },
                new int[] { -1, 1 }, new int[] { 1, -1 } };

        /// <summary>
        /// This function passess eetcode. runtime 54ms (beats 7.91%) and
        /// memory 52.94 MB (beats 26.98%)
        /// </summary>
        /// <param name="grid"></param>
        /// <returns></returns>
        public int ShortestPathBinaryMatrixDiagonalDistance_Working(int[][] grid)
        {
            int n = grid.Length;

            // we have to always follow o's path and avoid 1's
            // once we have visited a ndoe, we will not visit it again ,
            // so we can modify the grid to store the distance from the start point (where 0's were there originally)
            if (n == 0 || grid[0][0] != 0 || grid[n - 1][n - 1] != 0) return -1;

            Dictionary<(int, int), int> f_n = new();
            f_n[(0, 0)] = 0; // this cost does not matter since first vertex is dequed first and it will be the only one in the queue when it is dequed


            PriorityQueue<(int x, int y, int steps), int> pq = new();

            pq.Enqueue((0, 0, 1), f_n[(0, 0)]);

            int nx = -1;
            int ny = -1;
            int x, y, steps;
            int new_f_n, existing_f_n;

            while (pq.Count > 0)
            {
                new_f_n = existing_f_n = x = y = steps = nx = ny = -1;
                (x, y, steps) = pq.Dequeue();

                if (x == n - 1 && y == n - 1)
                {
                    return steps; // reached destination node
                }
                for (int i = 0; i < _directions.Length; i++)
                {
                    nx = x + _directions[i][0];
                    ny = y + _directions[i][1];
                    
                    // new node is valid only for valid values of nx & ny, and
                    // if it is not a wall (1) and
                    // if it is not visited before
                    if (nx < 0 || nx >= n || ny < 0 || ny >= n ||
                        grid[nx][ny] != 0
                        )
                    {
                        continue;
                    }

                    new_f_n = steps + 1 + Math.Max(Math.Abs(nx - (n - 1)), Math.Abs(ny - (n - 1))); 
                    if (f_n.TryGetValue((nx, ny), out existing_f_n) && existing_f_n <= new_f_n)
                    {
                        // Console.WriteLine($"skipping one node ({nx}, {ny}) since it is already in the queue with lesser f(n) value");
                        continue; // no need to enqueue this node since it is already in the queue and with lesser cost
                    }
                    f_n[(nx, ny)] = new_f_n;
                    pq.Enqueue((nx, ny, steps + 1), new_f_n); // f(n) = g(n) + h(n) where heuristic is Diagonal distance
                    
                }
            }

            // no path found
            return -1;

        }


        /// <summary>
        /// This function passess leetcode. runtime 30ms (beats 20.86%) and
        /// memory 49.86 MB (beats 29.50%)
        /// </summary>
        /// <param name="grid"></param>
        /// <returns></returns>
        public int ShortestPathBinaryMatrixDiagonalDistance_Working_faster(int[][] grid)
        {
            int n = grid.Length;

            // we have to always follow o's path and avoid 1's
            // once we have visited a ndoe, we will not visit it again ,
            // so we can modify the grid to store the distance from the start point (where 0's were there originally)
            if (n == 0 || grid[0][0] != 0 || grid[n - 1][n - 1] != 0) return -1;


            int[][] f_n = new int[n][];
            for (int i = 0; i < n; i++)
            {
                f_n[i] = new int[n];
                for (int j = 0; j < n; j++)
                {
                    f_n[i][j] = 0; // 0 means it was not given value .. note all values except firstcell are > 0
                }
            }


            PriorityQueue<(int x, int y, int steps), int> pq = new();

            pq.Enqueue((0, 0, 1), f_n[0][0]);

            int nx = -1;
            int ny = -1;
            int x, y, steps;
            int new_f_n, existing_f_n;

            while (pq.Count > 0)
            {
                new_f_n = existing_f_n = x = y = steps = nx = ny = -1;
                (x, y, steps) = pq.Dequeue();

                if (x == n - 1 && y == n - 1)
                {
                    return steps; // reached destination node
                }
                for (int i = 0; i < _directions.Length; i++)
                {
                    nx = x + _directions[i][0];
                    ny = y + _directions[i][1];

                    // new node is valid only for valid values of nx & ny, and
                    // if it is not a wall (1) and
                    // if it is not visited before
                    if (nx < 0 || nx >= n || ny < 0 || ny >= n ||
                        grid[nx][ny] != 0
                        )
                    {
                        continue;
                    }
                    existing_f_n = f_n[nx][ny];
                    new_f_n = steps + 1 + Math.Max(Math.Abs(nx - (n - 1)), Math.Abs(ny - (n - 1)));
                    if (existing_f_n != 0 && existing_f_n <= new_f_n)
                    {
                        // Console.WriteLine($"skipping one node ({nx}, {ny}) since it is already in the queue with lesser f(n) value");
                        continue; // no need to enqueue this node since it is already in the queue and with lesser cost
                    }
                    f_n[nx][ny] = new_f_n;
                    pq.Enqueue((nx, ny, steps + 1), new_f_n); // f(n) = g(n) + h(n) where heuristic is Diagonal distance

                }
            }

            // no path found
            return -1;

        }


        int nx = -1;
        int ny = -1;
        int x, y, steps;
        int new_f_n, existing_f_n;


        /// <summary>
        /// This function passess leetcode. runtime 26ms (beats 31.30%) and
        /// memory 49.35 MB (beats 30.22%)
        /// </summary>
        /// <param name="grid"></param>
        /// <returns></returns>
        public int ShortestPathBinaryMatrixDiagonalDistance_Working_even_faster(int[][] grid)
        {
            int n = grid.Length;

            // we have to always follow o's path and avoid 1's
            // once we have visited a ndoe, we will not visit it again ,
            // so we can modify the grid to store the distance from the start point (where 0's were there originally)
            if (n == 0 || grid[0][0] != 0 || grid[n - 1][n - 1] != 0) return -1;


            int[,] f_n = new int[n,n]; // will be initialized to 0' by default which is what we want. 0 means it was not given value .. note all values except firstcell are > 0


            PriorityQueue<(int x, int y, int steps), int> pq = new();

            pq.Enqueue((0, 0, 1), f_n[0,0]);

            

            while (pq.Count > 0)
            {
                new_f_n = existing_f_n = x = y = steps = nx = ny = -1;
                (x, y, steps) = pq.Dequeue();

                if (x == n - 1 && y == n - 1)
                {
                    return steps; // reached destination node
                }
                for (int i = 0; i < _directions.Length; i++)
                {
                    nx = x + _directions[i][0];
                    ny = y + _directions[i][1];

                    // new node is valid only for valid values of nx & ny, and
                    // if it is not a wall (1) and
                    // if it is not visited before
                    if (nx < 0 || nx >= n || ny < 0 || ny >= n ||
                        grid[nx][ny] != 0
                        )
                    {
                        continue;
                    }
                    existing_f_n = f_n[nx,ny];

                    new_f_n = steps + 1 + Math.Max(Math.Abs(nx - (n - 1)), Math.Abs(ny - (n - 1)));
                    if (existing_f_n != 0 && existing_f_n <= new_f_n)
                    {
                        // Console.WriteLine($"skipping one node ({nx}, {ny}) since it is already in the queue with lesser f(n) value");
                        continue; // no need to enqueue this node since it is already in the queue and with lesser cost
                    }
                    f_n[nx,ny] = new_f_n;
                    pq.Enqueue((nx, ny, steps + 1), new_f_n); 

                }
            }

            // no path found
            return -1;

        }


        public double TieBreakerh_n(int x, int y, int goalX, int goalY)
        {
            // Calculate the vector from the start to the goal
            double startToGoalX = goalX - 0; // Assuming start is at (0, 0)
            double startToGoalY = goalY - 0;
            // Calculate the vector from the current point to the goal
            double currentToGoalX = goalX - x;
            double currentToGoalY = goalY - y;
            // Calculate the cross product of the two vectors
            double crossProduct = startToGoalX * currentToGoalY - startToGoalY * currentToGoalX;
            // Return a small value based on the cross product to break ties
            return Math.Abs(crossProduct) * 0.001; // Adjust the multiplier as needed
        }


        void PrintPathAndWeights(int[][] grid, Dictionary<(int, int), (int, int)> path, int[][] weights, HashSet<(int x, int y)> visited,
            double[][] tie_breaker)
        {
            int n = weights.GetLength(0);

            // Implementation for printing the path
            var current = (n - 1, n - 1);
            Stack<(int, int)> s = new();
            while (current != (0, 0))
            {
                s.Push(current);
                current = path[current];
            }
            s.Push((0, 0));
            string output = string.Join(" -> ", s);
            Console.WriteLine(output);

            

            Console.WriteLine("f_n:");
            for (int i = 0; i < n; i++)
            {
                for (int j = 0; j < n; j++)
                {
                    Console.Write($"{grid[i][j] + weights[i][j]} ".PadRight(4));
                }
                Console.WriteLine();
            }

            Console.WriteLine("Path taken:");
            for (int i = 0; i < n; i++)
            {
                for (int j = 0; j < n; j++)
                {
                    if(s.Contains((i, j)))
                    {
                        Console.Write("P ");
                    }
                    else
                    {
                        Console.Write("X ");
                    }
                }
                Console.WriteLine();
            }

            Console.WriteLine("tiebreaker h_n:");
            for (int i = 0; i < n; i++)
            {
                for (int j = 0; j < n; j++)
                {
                    Console.Write($"{tie_breaker[i][j]} ".PadRight(6));
                }
                Console.WriteLine();
            }

            Console.WriteLine("All Visited Vertices:");
            for (int i = 0; i < n; i++)
            {
                for (int j = 0; j < n; j++)
                {
                    if(visited.Contains((i, j)))
                    {
                        Console.Write("V ");
                    }
                    else
                    {
                        Console.Write("X ");
                    }
                }
                Console.WriteLine();
            }
        }


        void PrintPath(Dictionary<(int, int), (int, int)> path)
        {
            // Implementation for printing the path
            var current = (_n - 1, _n - 1);
            Stack<(int, int)> s = new();
            while (current != (0, 0))
            {
                s.Push(current);
                current = path[current];
            }
            s.Push((0, 0));
            string output = string.Join(" -> ", s);
            Console.WriteLine(output);

            for (int i = 0; i < _n; i++)
            {
                for (int j = 0; j < _n; j++)
                {
                    Console.Write($"{_weights[i][j]} ");
                }
                Console.WriteLine();
            }
        }

        public void Demo()
        {
            int[][] grid = new int[][]
            {
                new int[] { 0, 1 },
                new int[] { 1, 0 }
            };
            // Console.WriteLine(ShortestPathBinaryMatrix(grid)); // output : 2, path is (0,0) -> (1,1)

            grid = [[0, 0, 0], [1, 1, 0], [1, 1, 0]];
            // Console.WriteLine(ShortestPathBinaryMatrix(grid)); // output : 4, path is (0,0) -> (0,1) -> (0,2) -> (1,2) -> (2,2)

            grid = [[0, 0, 0, 0, 1, 1], [0, 1, 0, 0, 1, 0], [1, 1, 0, 1, 0, 0], [0, 1, 0, 0, 1, 1], [0, 1, 0, 0, 0, 1], [0, 0, 1, 0, 0, 0]];
            // Console.WriteLine(ShortestPathBinaryMatrix(grid));

            grid = [[0, 0, 0], [1, 0, 0], [1, 1, 0]];
            // Console.WriteLine(ShortestPathBinaryMatrixDiagonalDistance(grid));

            grid = [[0, 0, 0, 0, 1, 1, 1, 1, 0], [0, 1, 1, 0, 0, 0, 0, 1, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 1, 0, 0, 1, 1], [0, 0, 1, 1, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 1, 0, 0, 0], [0, 1, 0, 1, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 1, 0]];
            Console.WriteLine(ShortestPathBinaryMatrixDiagonalDistance_Working_even_faster(grid));
        }
    }
}
